all: build

target/release/step0_repl: build
target/release/step1_read_print: build
target/release/step2_eval: build
target/release/step3_env: build

build:
	cargo build --release

clean:
	rm -rf target
