all: build

target/release/step0_repl: build
target/release/step1_read_print: build
target/release/step2_eval: build
target/release/step3_env: build
target/release/step4_if_fn_do: build
target/release/step5_tco: build
target/release/step6_file: build

build:
	cargo build --release

clean:
	rm -rf target
